"""Template Engine — renders resumes into templates (Typst, HTML, text).

Templates are stored in the templates/ directory and can be hot-swapped.
Each template directory has: template.typ, metadata.yaml, theme.json
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import structlog

logger = structlog.get_logger("careerforge.templates")

TEMPLATES_DIR = Path(__file__).resolve().parent.parent.parent.parent.parent / "templates"


@dataclass
class TemplateInfo:
    """Metadata about a template."""
    name: str
    display_name: str = ""
    description: str = ""
    author: str = ""
    version: str = "1.0"
    page_size: str = "letter"
    font_family: str = "Inter"
    font_size: int = 10
    supports_color: bool = True

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "display_name": self.display_name,
            "description": self.description,
            "author": self.author,
            "version": self.version,
            "page_size": self.page_size,
            "font_family": self.font_family,
            "font_size": self.font_size,
        }


class TemplateEngine:
    """Manages resume templates and renders them."""

    @staticmethod
    def list_templates() -> list[TemplateInfo]:
        """List all available templates."""
        if not TEMPLATES_DIR.exists():
            return []

        templates = []
        for template_dir in TEMPLATES_DIR.iterdir():
            if not template_dir.is_dir():
                continue
            metadata_file = template_dir / "metadata.yaml"
            if not metadata_file.exists():
                continue

            temp_info = TemplateInfo(name=template_dir.name)

            # Try to load metadata
            try:
                import yaml
                meta = yaml.safe_load(metadata_file.read_text(encoding="utf-8"))
                if meta:
                    temp_info = TemplateInfo(
                        name=template_dir.name,
                        display_name=meta.get("display_name", template_dir.name),
                        description=meta.get("description", ""),
                        author=meta.get("author", ""),
                        version=meta.get("version", "1.0"),
                        page_size=meta.get("page_size", "letter"),
                        font_family=meta.get("font_family", "Inter"),
                        font_size=meta.get("font_size", 10),
                    )
            except Exception:
                pass

            templates.append(temp_info)

        return templates

    @staticmethod
    def get_template(name: str) -> TemplateInfo | None:
        """Get a specific template by name."""
        for t in TemplateEngine.list_templates():
            if t.name == name:
                return t
        return None

    @staticmethod
    def get_template_path(name: str) -> Path:
        """Get the path to a template directory."""
        return TEMPLATES_DIR / name

    @staticmethod
    def get_typst_source(name: str) -> str:
        """Get the Typst source for a template."""
        typst_file = TEMPLATES_DIR / name / "template.typ"
        if not typst_file.exists():
            return TemplateEngine._default_typst()
        return typst_file.read_text(encoding="utf-8")

    @staticmethod
    def render_to_typst(resume: dict[str, Any], template: str = "modern") -> str:
        """Render a canonical resume to Typst format."""
        sections = resume.get("sections", [])
        candidate = {
            "name": resume.get("candidate_name", ""),
            "email": resume.get("email", ""),
            "phone": resume.get("phone", ""),
            "location": resume.get("location", ""),
            "linkedin": resume.get("linkedin_url", ""),
            "github": resume.get("github_url", ""),
        }

        typst = f"""// Generated by CareerForge AI
// Template: {template}
#set page(paper: "us-letter", margin: (x: 0.7in, y: 0.5in))
#set text(font: ("Inter", "Helvetica", "Arial"), size: 10pt)

// Header
#align(center + top)[
  #text(size: 22pt, weight: "bold")[{candidate["name"]}]
  #v(2pt)
  #text(size: 9pt)[{candidate["email"]} | {candidate["phone"]} | {candidate["location"]}]
  #text(size: 9pt)[
    #if candidate["linkedin"] != "" [[LinkedIn]({candidate["linkedin"]}) #h(8pt)]
    #if candidate["github"] != "" [[GitHub]({candidate["github"]})]
  ]
]

#line(length: 100%)
#v(8pt)
"""
        for section in sections:
            name = section.get("name", "")
            items = section.get("items", [])
            if not items:
                continue

            typst += f"""
// {name} Section
#text(size: 11pt, weight: "bold")[{name}]
#line(length: 100%)
"""
            for item in items:
                text = item.get("text", "").strip()
                if text:
                    # Check if it has highlights/subsections
                    if name.lower() in ("experience", "projects", "education"):
                        parts = text.split("\n", 1)
                        main_line = parts[0] if parts else text
                        typst += f"  - {_escape_typst(main_line)}\n"
                        if len(parts) > 1:
                            typst += f"    {_escape_typst(parts[1])}\n"
                    else:
                        typst += f"  - {_escape_typst(text)}\n"

            typst += "#v(4pt)\n"

        return typst

    @staticmethod
    def render_to_text(resume: dict[str, Any]) -> str:
        """Render a canonical resume to plain text."""
        sections = resume.get("sections", [])
        candidate_name = resume.get("candidate_name", "")
        email = resume.get("email", "")
        phone = resume.get("phone", "")
        location = resume.get("location", "")

        text = f"{candidate_name}\n{email} | {phone} | {location}\n{'=' * 60}\n\n"

        for section in sections:
            name = section.get("name", "")
            items = section.get("items", [])
            if not items:
                continue
            text += f"{name.upper()}\n{'-' * 30}\n"
            for item in items:
                bullet = item.get("text", "").strip()
                if bullet:
                    text += f"• {bullet}\n"
            text += "\n"

        return text

    @staticmethod
    def _default_typst() -> str:
        """Return a default Typst template."""
        return """// CareerForge AI — Default Resume Template
#set page(paper: "us-letter", margin: (x: 0.7in, y: 0.5in))
#set text(font: ("Helvetica", "Arial"), size: 10pt)

#align(center)[
  #text(size: 20pt, weight: "bold")[CANDIDATE NAME]
  #v(4pt)
  #text(size: 9pt)[email | phone | location]
]

#line(length: 100%)
#v(8pt)

#text(size: 11pt, weight: "bold")[Section]
#line(length: 100%)
- Bullet point here
"""


def _escape_typst(text: str) -> str:
    """Escape special characters for Typst."""
    replacements = {
        "&": "\\&", "%": "\\%", "$": "\\$",
        "#": "\\#", "_": "\\_", "{": "\\{",
        "}": "\\}", "[": "\\[", "]": "\\]",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text
