"""Resume Blueprint — the strategic plan generated BEFORE any writing.

The blueprint is produced by the Resume Planner Agent and determines
what evidence to use, how to structure the resume, and which
keywords to emphasize. It is stored as the planning record.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

import structlog

logger = structlog.get_logger("careerforge.resume.blueprint")


@dataclass
class EvidenceMapping:
    """Maps a section to its evidence sources."""
    section: str
    evidence_type: str  # experience, project, skill, certificate, etc.
    evidence_ids: list[str] = field(default_factory=list)
    priority: int = 0  # Higher = more important for this section
    key_themes: list[str] = field(default_factory=list)
    word_count_target: int = 0


@dataclass
class ResumeBlueprint:
    """Complete strategic plan for resume generation.

    Generated by the Resume Planner Agent before any content is written.
    Stored as the planning record alongside the generated resume.
    """
    # Identity
    id: str = ""
    created_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    # Target
    target_role: str = ""
    target_industry: str = ""
    company: str = ""

    # Strategy
    resume_strategy: str = ""  # e.g., "technical", "executive", "career-change"
    summary_focus: str = ""
    tone: str = "professional"

    # Sections
    sections: list[dict[str, Any]] = field(default_factory=list)

    # Evidence mapping
    evidence_mappings: list[EvidenceMapping] = field(default_factory=list)

    # Keyword analysis
    keywords_to_emphasize: list[str] = field(default_factory=list)
    keywords_missing: list[str] = field(default_factory=list)

    # Scoring
    ats_coverage_estimate: float = 0.0
    confidence_score: float = 0.0
    reasoning: str = ""

    # Metadata
    job_profile_version: str = ""
    evidence_bundle_version: str = ""
    prompt_version: str = ""
    model_used: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "created_at": self.created_at,
            "target_role": self.target_role,
            "target_industry": self.target_industry,
            "company": self.company,
            "resume_strategy": self.resume_strategy,
            "summary_focus": self.summary_focus,
            "tone": self.tone,
            "sections": self.sections,
            "evidence_mappings": [
                {
                    "section": em.section,
                    "evidence_type": em.evidence_type,
                    "evidence_ids": em.evidence_ids,
                    "priority": em.priority,
                    "key_themes": em.key_themes,
                    "word_count_target": em.word_count_target,
                }
                for em in self.evidence_mappings
            ],
            "keywords_to_emphasize": self.keywords_to_emphasize,
            "keywords_missing": self.keywords_missing,
            "ats_coverage_estimate": self.ats_coverage_estimate,
            "confidence_score": self.confidence_score,
            "reasoning": self.reasoning,
            "prompt_version": self.prompt_version,
            "model_used": self.model_used,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ResumeBlueprint:
        mappings = []
        for em_data in data.get("evidence_mappings", []):
            mappings.append(EvidenceMapping(
                section=em_data.get("section", ""),
                evidence_type=em_data.get("evidence_type", ""),
                evidence_ids=em_data.get("evidence_ids", []),
                priority=em_data.get("priority", 0),
                key_themes=em_data.get("key_themes", []),
                word_count_target=em_data.get("word_count_target", 100),
            ))

        return cls(
            id=data.get("id", ""),
            created_at=data.get("created_at", ""),
            target_role=data.get("target_role", ""),
            target_industry=data.get("target_industry", ""),
            company=data.get("company", ""),
            resume_strategy=data.get("resume_strategy", ""),
            summary_focus=data.get("summary_focus", ""),
            tone=data.get("tone", "professional"),
            sections=data.get("sections", []),
            evidence_mappings=mappings,
            keywords_to_emphasize=data.get("keywords_to_emphasize", []),
            keywords_missing=data.get("keywords_missing", []),
            ats_coverage_estimate=data.get("ats_coverage_estimate", 0.0),
            confidence_score=data.get("confidence_score", 0.0),
            reasoning=data.get("reasoning", ""),
            prompt_version=data.get("prompt_version", ""),
            model_used=data.get("model_used", ""),
        )
